/*
File Name:Lab5Task1.cpp
Written By: Naveed Amjad
Roll No: BITF19M541
Date: 25/03/20
Description: to calculate the income generated by ticket sales

*/

#include <iostream>
using namespace std;
int main ()
{
	// variable declaratiom and initialization
	
	int classAcost=15 , classBcost=12 , classCcost=9;
	int ticketA, ticketB, ticketC;
	
	cout <<"Enter number of tickets sold for category A: "<<endl; // To tell user what to do 
	
	cin >> ticketA;  			// to store value of tickets sold of type A
	
		cout <<"Enter number of tickets sold for category B: "<<endl;	// user will know what to do now
		
		cin >> ticketB;			// to store value of tickets sold of type A
		
		cout <<"Enter number of tickets sold for category C: "<<endl;	// user will know whta to do now
		
		cin >> ticketC;			// to store value of tickets sold of type C
	
	int A,B,C;		// variable initialization	
	
	A=ticketA * classAcost;		// to calculate income of category A
	
	B=ticketB * classBcost;		// to calculate income of category B
	
	C=ticketC *classCcost;		// to calculate income of category C
	
	cout <<"Total income = " <<A+B+C << endl;		// calculation and display of total income 
	
	
	
	
	
	
	
	return 0;
}
